♻️ refactor(typescript):  react to typscript for folder react
p3ol/oak pull request #1397
Opened 2024-05-29 11:22 UTC by mehdiezz21

React to typscript for folder react. There are very few guys left to mark. But a comment is present on each.

2024-05-30 13:57 UTC, maximedasilva requested changes
nicely done ! 

What left to do, reword the rollup conf as it not buyild anymore, check the stories and pass it in tsx too, rewrite the tests in typescript and the snapshots too

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Editable/Form.tsx
> +            ((component.settings as any)?.fields || []) // TODO FIX IT
Why this any ? ComponentsSettingsFormObject does not fit ?

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Editable/Form.tsx
> +              title={<Text>{ tab.title as string }</Text> as any} // TODO FIX IT
Why this as any ? I think its useless

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Editable/Form.tsx
> +                                    // overrides={overrides}
Why removing this ?

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Element/index.d.ts
useless as we generate them from ts files

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Element/index.tsx
> +interface ElementProps {
extends form ComponentsPropsWithoutRef

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Element/index.tsx
> +interface editableRefObject {
Interface and types starts with upeer case

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Element/index.tsx
> +  const innerRef = useRef<Ref<HTMLElement>>();
looks weird, i think you wanted to do 
`const innerRef = useRef<HTMLElement>();`

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Element/index.tsx
> +    (override as FieldOverride | ComponentOverride)?.render ||
Try to use Object outside of core package

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Icon/index.d.ts
useless as we generate them from ts files

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Option/index.tsx
> +interface OptionProps {
extends from ComponentPropsWithRef

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Icon/index.tsx
> +interface IconProps {
extends from ComponentPropsWithoutRef

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Option/index.d.ts
useless as we generate them from ts files

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Option/index.tsx
> +  const innerRef = useRef<Ref<HTMLElement>>();
useRef<HTMLElement>()

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Text/index.d.ts
useless as we generate them fro ts

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Text/index.ts
> +interface TextProps {
extends from CompontPropsWIthoutRef

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Button/index.d.ts
useless as its generated from ts files

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Button/index.tsx
> +interface ButtonProps {
extends from ComponentPropfsWithRef

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Col/index.d.ts
useless as its generated from ts

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Col/index.tsx
> +interface ColProps {
extends from ComponentPropsWithoutRef

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Col/index.tsx
> +interface editableRefObject {
interface and types starts with an upper case

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Col/index.tsx
>            >
why removing the container ?

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/EmptySpace/index.d.ts
Useless as its generated from ts files

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Foldable/index.d.ts
useless   as its generates from ts

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/Container/index.tsx
> -                index={i}
why removing this ?

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Foldable/index.tsx
> +interface FoldableProps {
extends from ComponentpropsWithoutRef

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Image/index.d.ts
Useless as its generated from ts files

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Image/index.tsx
> +interface ImageProps {
extends from ComponentPropsWithoutRef

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Image/index.tsx
> +          backgroundImage: element.url ? `url('${element.url}')` : undefined,
Why setting undefined and not null ?

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Row/index.d.ts
Useless as its generated from ts files

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Row/index.tsx
> +interface RowProps {
extends from ComponentPropfsWithoutRef

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Text/index.d.ts
Useless as its generated from ts files

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Text/index.tsx
> +interface TextProps {
Extend from ComponentPropsWithoutRef

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Title/index.d.ts
Useless as its generated from ts files

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/components/Title/index.tsx
> +interface TitleProps {
extends from ComponentPropfsWithoutRef

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/fields/ImageField/index.d.ts
Useless as its generated from ts files

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/fields/ImageField/index.tsx
> +export declare type imageFieldObject = {
extends from ComponentPropsWIthoutRef

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/fields/ImageField/index.tsx
> +export declare type imageFieldObject = {
Also, Interfaces and types start with an upper case

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/fields/ImageField/index.tsx
> +export declare type imageFieldContent<T = any> = {
Interfaces and types start with an upper Case

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/fields/ImageField/index.tsx
> +  setting?: ComponentSettingsFieldObject | ComponentSettingsField;
use Object only

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/fields/ImageField/index.tsx
> +  const onFile = async (e: Event) => {
watch what we did on junipero, but usehtml event is not recommanded

2024-05-30 13:57 UTC, maximedasilva commented on packages/react/lib/fields/index.d.ts
Useless as its generated from ts files

2024-05-30 14:16 UTC, mehdiezz21 commented on packages/react/lib/Builder/index.tsx
> -              index={i}
because we don't use index at all in Element

2024-05-30 14:16 UTC, mehdiezz21 commented on packages/react/lib/Container/index.tsx
> -                index={i}
because we don't use index at all in Element

2024-05-30 14:19 UTC, maximedasilva commented on packages/react/lib/Builder/index.tsx
> -              index={i}
Yes, but when using componentPropsWithoutRef we can add props we do not explicitly declare in the component, and the id is important though

2024-06-07 08:45 UTC, dackmin approved these changes

2024-06-07 08:45 UTC, merged