✨ feat(editable): update for display panel modal TUR-102
p3ol/oak pull request #1433
Opened 2024-07-01 14:07 UTC by mehdiezz21

Update Editable for display panel modal.

https://github.com/p3ol/oak/assets/72040763/aaa64a38-f7ee-41a1-9a75-70e0671d75de

2024-07-01 14:12 UTC, maximedasilva commented
may be I'm wrong, but I thought the editable type was an option passed to the builder to allow us to use floating or modal when defining a new oak Builder

2024-07-02 06:08 UTC, dackmin commented
> Ugo Stephant 24/06/2024 15h06
editableType: 'floating' (default) | 'panel'

2024-07-04 08:16 UTC, dackmin requested changes
`editableType` needs to be a `BuilderOption` available on both core & the react renderer, it's retrieved from `useBuilder` here but doesn't come from anywhere. 
Add it to `packages/core/lib/classes.ts:BuilderOptions` & `packages/core/lib/types.ts:BuilderObject` and start from here.

2024-07-04 08:40 UTC, dackmin commented
can you add a story for the modal type?

2024-07-04 08:57 UTC, dackmin requested changes

2024-07-04 08:57 UTC, dackmin commented on packages/react/lib/components/Col/index.tsx
> +  const modalRef: MutableRefObject<ModalRef> = useRef();
`const modalRef = useRef<ModalRef>();`

2024-07-04 08:57 UTC, dackmin commented on packages/react/lib/Element/index.tsx
> +  const modalRef: MutableRefObject<ModalRef> = useRef();
`const modalRef = useRef<ModalRef>();`

2024-07-04 08:57 UTC, dackmin commented on packages/react/lib/Editable/Modal.tsx
> +export declare interface FloatingRef extends OakRef {
remove this, I don't think it's used inside Modal

2024-07-04 08:57 UTC, dackmin commented on packages/react/lib/Editable/Modal.tsx
> +import { useBuilder } from '../hooks';
move before form

2024-07-04 08:57 UTC, dackmin commented on packages/react/lib/Editable/index.tsx
> +  modalRef?: MutableRefObject<ModalRef>;
ModalRef is already a MutableRefObject, you can just use ModalRef

2024-07-04 08:57 UTC, dackmin commented on packages/react/lib/Editable/index.tsx
> +  open?: () => void;
FloatingRef is not used here, remove it

2024-07-04 08:57 UTC, dackmin commented on packages/react/lib/Editable/index.tsx
> +  current?: FloatingRef | HTMLDivElement | null;
current does not exist

2024-07-04 09:23 UTC, dackmin approved these changes

2024-07-04 12:33 UTC, maximedasilva requested changes

2024-07-04 12:33 UTC, maximedasilva commented on packages/react/lib/Editable/Floating.tsx
> +import type {
import full type first

2024-07-04 12:33 UTC, maximedasilva commented on packages/react/lib/Editable/Modal.tsx
> +import type {
import full type first

2024-07-04 12:33 UTC, maximedasilva commented on packages/react/lib/Editable/index.tsx
>    ComponentObject,
import full type first

2024-07-04 12:33 UTC, maximedasilva commented on packages/react/lib/Editable/index.tsx
>  import {
its a full type import

2024-07-04 12:33 UTC, maximedasilva commented on packages/react/lib/components/Col/index.tsx
>  import type { ComponentObject, ComponentOverrideObject, ElementObject } from '@oakjs/core';
import full type first

2024-07-08 05:51 UTC, merged