🐛fix: oak text editor font size
p3ol/oak pull request #405
Opened 2021-07-29 14:55 UTC by maximedasilva

This fix editor base font size to avoid text increasing in editor to result in smaller text in component. 

In addition, I also added some translations for all the content editor tooltips.

2021-07-30 14:43 UTC, dackmin requested changes

2021-07-30 14:43 UTC, dackmin commented on packages/oak-addon-basic-components/lib/core/Editor/ColorButton.js
> +          <Text>{t => t('addons.basicComponents.fields.editor.color',
```jsx
<Text
  name="addons.basicComponents.fields.editor.color"
  default="Color"
/>
```

2021-07-30 14:43 UTC, dackmin commented on packages/oak-addon-basic-components/lib/core/Editor/index.js
> +              <Text>{t => t('addons.basicComponents.fields.editor.bold',
use `name` & `default` props instead

2021-07-30 14:43 UTC, dackmin commented on packages/oak-addon-basic-components/lib/core/Editor/BlockButton.js
> +import { Tooltip } from '@poool/junipero';
import classNames from `@poool/junipero` directly

2021-07-30 16:03 UTC, dackmin requested changes

2021-07-30 16:03 UTC, dackmin commented on packages/oak-addon-basic-components/lib/core/Editor/BlockButton.js
> +        <i className="oak-icons">{ icon }</i>
use `<Icon>{ icon }</Icon>`

2021-07-30 16:25 UTC, maximedasilva commented
I still have a problem with a traduction key (Bold to be precise), in english no text is rendered and I have this error 
![Capture d’écran 2021-07-30 à 18 24 23](https://user-images.githubusercontent.com/10706836/127682875-95f32e65-adcb-4d13-8359-f70b578529d5.png)

It seems to come from `junipero-utils/get` function

2021-08-02 08:32 UTC, dackmin commented
The `.get` problem comes from poorly written code inside junipero-utils: https://github.com/p3ol/junipero/issues/598
I'll release a patch and update your PR once it is available on npm.

2021-08-02 09:22 UTC, merged