📖  docs: add v1 docs
p3ol/oak pull request #670
Opened 2022-03-07 15:54 UTC by dackmin

2022-03-07 16:33 UTC, emileNetter approved these changes

2022-03-08 09:28 UTC, maximedasilva requested changes

2022-03-08 09:28 UTC, maximedasilva commented on packages/oak/README.md
> +  components: [{
it has to be 
```
render(element, { addons: [{
  components: [{
  }],
  fieldTypes : [{
  }]
]});
```
no ?

2022-03-08 09:28 UTC, maximedasilva commented on packages/oak/README.md
> +Defines a list of components/fields to override. See [overrides](#overrides) for more information.
only components are overridable for now no ?

2022-03-08 10:55 UTC, maximedasilva approved these changes

2022-03-08 11:48 UTC, merged